name: Build image
on:
  workflow_dispatch:

jobs:
  # JOB to run change detection

  build-jammy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup build dependencies
        run: .github/workflows/setup-dependencies.sh

      - name: Build image
        run: .github/workflows/build.sh jammy-rt-ros2

  # TODO: release image
